// Mocks generated by Mockito 5.4.4 from annotations
// in magic_ai_fit/test/features/workout/presentation/viewmodels/workout_list_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:magic_ai_fit/core/error/failures.dart' as _i6;
import 'package:magic_ai_fit/core/usecases/usecase.dart' as _i8;
import 'package:magic_ai_fit/features/workout/domain/entities/workout.dart'
    as _i7;
import 'package:magic_ai_fit/features/workout/domain/repositories/workout_repository.dart'
    as _i2;
import 'package:magic_ai_fit/features/workout/domain/usecases/delete_workout.dart'
    as _i9;
import 'package:magic_ai_fit/features/workout/domain/usecases/get_workouts.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWorkoutRepository_0 extends _i1.SmartFake
    implements _i2.WorkoutRepository {
  _FakeWorkoutRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetWorkouts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWorkouts extends _i1.Mock implements _i4.GetWorkouts {
  MockGetWorkouts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkoutRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WorkoutRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Workout>>> call(
          _i8.NoParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Workout>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Workout>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Workout>>>);
}

/// A class which mocks [DeleteWorkout].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteWorkout extends _i1.Mock implements _i9.DeleteWorkout {
  MockDeleteWorkout() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.WorkoutRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeWorkoutRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.WorkoutRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
          _i9.DeleteWorkoutParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);
}
