// Mocks generated by Mockito 5.4.4 from annotations
// in magic_ai_fit/test/features/workout/data/repositories/workout_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:magic_ai_fit/features/workout/data/datasources/workout_local_data_source.dart'
    as _i2;
import 'package:magic_ai_fit/features/workout/data/models/workout_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WorkoutLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkoutLocalDataSource extends _i1.Mock
    implements _i2.WorkoutLocalDataSource {
  MockWorkoutLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.WorkoutModel>> getWorkouts() => (super.noSuchMethod(
        Invocation.method(
          #getWorkouts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.WorkoutModel>>.value(<_i4.WorkoutModel>[]),
      ) as _i3.Future<List<_i4.WorkoutModel>>);

  @override
  _i3.Future<void> cacheWorkout(_i4.WorkoutModel? workoutToCache) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWorkout,
          [workoutToCache],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateWorkout(_i4.WorkoutModel? workout) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWorkout,
          [workout],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWorkout(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWorkout,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
